Controllers/DashBoardController.cs
using Microsoft.AspNetCore.Mvc;
using Practico.Controllers.Attributes;
using Practico.DatabaseController;
using Practico.Models;

namespace Practico.Controllers
{
    [LoginAuth]
    public class DashBoardController : Controller
    {
        private readonly MyContext context;
        public tbUser tbUser { get; set; }
        public tbSurvey tbSurvey { get; set; }
        public DashBoardController(MyContext context)
        {
            this.context = context;
            tbUser = new tbUser(context);
            tbSurvey = new tbSurvey(context);
        }


        public IActionResult Index()
        {
            if (int.Parse(HttpContext.Session.GetString("IdRole")) == 3)
            {
                return RedirectToAction("Employee");
            }
            DateTime today = DateTime.Today;
            ViewBag.time = tbSurvey.GetLastSurveyDateByBoss(int.Parse(HttpContext.Session.GetString("UserId")));
            if (ViewBag.time < today)
                return RedirectToAction("BossFormPost");
            List<int> counter = new List<int>() { 0, 0, 0, 0, 0 };
            List<SurveyAnswerQuestion> surveyAnswerQuestions = context.SurveysAnswersQuestions.ToList();
            List<DateTime> dates = new List<DateTime>();
            List<Tuple<int, int>> values = new List<Tuple<int, int>>();
            List<string> datesValue = new List<string>();
            List<double> valuesRtn = new List<double>();
            DashBoardModel model = new DashBoardModel();
            model.count = new List<int>();
            foreach (var item in surveyAnswerQuestions)
            {
                Survey s = context.Surveys.Where(x => x.Id == item.IdSurvey).FirstOrDefault();
                if (context.BossEmployees.Where(x => ((x.IdEmployee == s.IdEmployee) && (x.IdBoss == int.Parse(HttpContext.Session.GetString("UserId"))))).FirstOrDefault() != null)
                {
                    counter[item.Answer - 1]++;

                    if (dates.Count == 0)
                    {
                        dates.Add(s.DateTime);
                        values.Add(new Tuple<int, int>(1, item.Answer));
                    }
                    else if (dates[dates.Count - 1].Year == s.DateTime.Year &&
                        dates[dates.Count - 1].Month == s.DateTime.Month && dates[dates.Count - 1].Day == s.DateTime.Day)
                    {

                        values[values.Count - 1] = new Tuple<int, int>(values[values.Count - 1].Item1 + 1, values[values.Count - 1].Item2 + item.Answer);
                    }
                    else
                    {
                        dates.Add(s.DateTime);
                        values.Add(new Tuple<int, int>(1, item.Answer));
                    }
                }

            }
            for (int i = 0; i < values.Count; i++)
            {
                valuesRtn.Add((double)values[i].Item2 / (double)values[i].Item1);
                datesValue.Add(dates[i].ToString("dd/MM/yyyy"));
            }

            model.count = counter;
            model.dates = datesValue;
            model.values = valuesRtn;
            model.Users = tbUser.EmployeesByBossId(int.Parse(HttpContext.Session.GetString("UserId")));
            return View(model);
        }

        [HttpGet]
        public IActionResult Employee()
        {
            ViewBag.time = tbSurvey.GetLastSurveyDateByEmployee(int.Parse(HttpContext.Session.GetString("UserId")));

            List<Question> list = context.Questions.Where(x => (x.ForEmployee == 1 && x.Default == 1)).ToList();
            return View(list);
        }

        public IActionResult RemoveUser(int userId)
        {
            foreach (var item in context.Users.ToList())
            {
                if (item.Id == userId)
                {
                    context.Remove(item);
                    context.SaveChanges();
                }

            }
            foreach (var item in context.Surveys)
            {
                if (item.IdEmployee == userId)
                {
                    foreach (var item2 in context.SurveysAnswersQuestions)
                    {
                        if (item2.IdSurvey == item.Id)
                        {
                            context.Remove(item2);
                            context.SaveChanges();
                        }
                    }
                    context.Remove(item);
                    context.SaveChanges();
                }

            }
            foreach (var item in context.BossEmployees)
            {
                if (item.IdEmployee == userId)
                {
                    context.Remove(item);
                    context.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult BossFormPost()
        {
            ViewBag.time = tbSurvey.GetLastSurveyDateByBoss(int.Parse(HttpContext.Session.GetString("UserId")));

            List<Question> list = context.Questions.Where(x => (x.ForBoss == 1 && x.Default == 1)).ToList();
            return View("Employee", list);
        }

        [HttpGet]
        public IActionResult EmployeeMoodDetail(int IdUser)
        {
            List<Survey> su = context.Surveys.Where(x => x.IdEmployee == IdUser).ToList();
            List<SurveyAnswerQuestion> ass = new List<SurveyAnswerQuestion>();
            EmployeeDetail detail = new EmployeeDetail();
            detail.sum = new List<double>();
            detail.dateTimes = new List<string>();
            foreach (var item in su)
            {
                var sur = context.SurveysAnswersQuestions.Where(x => x.IdSurvey == item.Id).ToList();
                double s = 0;
                foreach (var question in sur)
                {
                    s += question.Answer;
                }
                if (sur.Count > 0)
                    s = s / sur.Count;

                detail.sum.Add(s);
                detail.dateTimes.Add(item.DateTime.ToString("MM/dd/yyyy HH:mm"));
            }
            return View(detail);
        }

        [HttpPost]
        public IActionResult FormPost(IFormCollection form)
        {
            if (int.Parse(HttpContext.Session.GetString("IdRole")) == 3)
            {
                tbSurvey.AddSuveyToEmployee(form, int.Parse(HttpContext.Session.GetString("UserId")));
            }
            else
            {
                tbSurvey.AddSuveyToEmployee(form, 0, int.Parse(HttpContext.Session.GetString("UserId")));
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult logout()
        {
            HttpContext.Session.SetString("UserId", "");
            HttpContext.Session.SetString("UserName", "");
            HttpContext.Session.SetString("IdRole", "");
            return RedirectToAction("Index", "Home");
        }


        [HttpGet]
        public IActionResult EmployeeEdit(int IdUser)
        {
            User? user = tbUser.GetUserById(IdUser);
            return View(user);
        }

        [HttpPost]
        public IActionResult EmployeeEdit(User user)
        {
            tbUser.EditEmployee(user);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult AddEmployes(int countEmp)
        {
            tbUser.AddMoreEmployeesToBoss(int.Parse(HttpContext.Session.GetString("UserId")), countEmp);
            return RedirectToAction("Index");
        }
    }
}

Views/DashBoard/Employee.cshtml
@{
    Layout = "~/Views/Shared/_LayoutDashBoard.cshtml";
}

@model List<Question>

@{
    DateTime todayMidnight = DateTime.Today;
}

@if (ViewBag.time < todayMidnight)
{


    <div class="container-fluid">
        <div style="margin-right:5vw;margin-left:5vw;width:auto" class="card shadow mb-4">
            <div class="card-header py-3">
                <h4 class="m-0 font-weight-bold text-primary">Dotazník</h4>
            </div>
            <div class="card-body" style="width:auto">
                <div class="table-responsive">
                    <form asp-action="FormPost" asp-controller="DashBoard">
                        <input id="counter" type="hidden" value="0" />
                        @foreach (Question question in Model)
                        {
                            <div class="mb-3">
                                <label style="font-size:20px;font-weight:bold" for="exampleInputEmail1" class="form-label">@question.Name</label>
                                @{
                                    var id2 = question.Id.ToString() + "q";
                                }
                                <input id="@id2" type="hidden" name="@question.Id;" value="@question.Id" />
                                <div class="row row-cols-5 justify-content-md-center" id="select1">
                                    <div class="col-md-auto">
                                        @{
                                            id2 = question.Id.ToString() + "1";
                                        }
                                        <img id="@id2" onclick="SetSize(@question.Id,1)" style="height:5vw;padding:0px" class="rounded mx-auto d-block" src="/dashboard/img/smile1.png" />
                                    </div>
                                    <div class="col-md-auto">
                                        @{
                                            id2 = question.Id.ToString() + "2";
                                        }
                                        <img id="@id2" onclick="SetSize(@question.Id,2)" style="height:5vw;padding:0px" class="rounded mx-auto d-block" src="/dashboard/img/smile2.png" />
                                    </div>
                                    <div class="col-md-auto">
                                        @{
                                            id2 = question.Id.ToString() + "3";
                                        }
                                        <img id="@id2" onclick="SetSize(@question.Id,3)" style="height:5vw;padding:0px" class="rounded mx-auto d-block" src="/dashboard/img/smile3.png" />
                                    </div>
                                    <div class="col-md-auto">
                                        @{
                                            id2 = question.Id.ToString() + "4";
                                        }
                                        <img id="@id2" onclick="SetSize(@question.Id,4)" style="height:5vw;padding:0px" class="rounded mx-auto d-block" src="/dashboard/img/smile4.png" />
                                    </div>
                                    <div class="col-md-auto">
                                        @{
                                            id2 = question.Id.ToString() + "5";
                                        }
                                        <img id="@id2" onclick="SetSize(@question.Id,5)" style="height:5vw;padding:0px" class="rounded mx-auto d-block" src="/dashboard/img/smile5.png" />
                                    </div>
                                </div>
                            </div>
                        }
                        <button style="font-size:120%" type="submit" id="buttSub" class="btn btn-primary" disabled>Odeslat</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="container-fluid">
        <div class="card bg-success text-white mb-3 shadow" style="max-width: 40rem;">
            <div class="row">
            <div class="card-body">
                   
                       
                <h3 style="font-weight:bold" class="card-text">
                            <div class="row">
                                <div class="col-md-auto">
                    Dotazník byl již odeslán. Moc si toho vážíme!
                                </div>
                                <div class="col-md-auto">
                                    <img style="height:40px" src="/dashboard/img/smile6.png" />
                                </div>
                            </div>
                </h3>



                </div>
        </div>
    </div>
    </div>
}
<script>
   function SetSize(s,id)
   {
       var res = s.toString();
        res += id.toString();
        document.getElementById(res).style.height = '7vw';
        document.getElementById(res).style.opacity = 1;
        document.getElementById(s.toString() + "q").name = s.toString() + ";";
        document.getElementById(s.toString()+"q").name += id.toString();
       for(var i = 1; i < 6; i++)
       {
         var test = s.toString() + i.toString();
         if(test != res)
         {
                document.getElementById(res).style.height = '5vw';
                document.getElementById(test).style.opacity = 0.3;
         }
         else
         {
                document.getElementById('counter').setAttribute('value', parseInt(document.getElementById('counter').getAttribute('value')) + 1);
                if (parseInt(document.getElementById('counter').getAttribute('value')) >=3)
                {
                    document.getElementById('buttSub').disabled = false;
                }
         }
       }
   }
</script>

Views/DashBoard/EmployeeEdit.cshtml
@{
    Layout = "~/Views/Shared/_LayoutDashBoard.cshtml";
}

@model User;


<div style="margin: 15px" class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Ůprava zaměstance</h6>
    </div>
    <div class="card-body">
        <form class="row g-3" asp-action="EmployeeEdit" asp-controller="DashBoard">
            <input type="number" value="@Model.Id" asp-for="Id" hidden>
            <input type="text" value="@Model.Name" asp-for="Name" hidden>
            <input type="text" value="@Model.Password" asp-for="Password" hidden>
            <div class="col-md-6">
                <label for="inputEmail4" class="form-label">Jméno</label>
                <input type="text" class="form-control" id="inputEmail4" value="@Model.FirstName" asp-for="FirstName" required>
            </div>
            <div class="col-md-6">
                <label for="inputPassword4" class="form-label">Příjmení</label>
                <input type="text" class="form-control" id="inputPassword4" value="@Model.Surname" asp-for="Surname" required>
            </div>
            <div class="col-12">
                <label for="inputAddress" class="form-label">Email</label>
                <input type="email" class="form-control" id="inputAddress" value="@Model.Email" asp-for="Email">
            </div>
            <div class="col-12">
                <button type="submit" class="btn btn-primary">Upravit uživatele</button>
            </div>
        </form>
    </div>
</div>

Views/DashBoard/EmployeeMoodDetail.cshtml
@{
    Layout = "~/Views/Shared/_LayoutDashBoard.cshtml";
}

@model EmployeeDetail
<script src="~/dashboard/vendor/chart.js/Chart.min.js"></script>
<div style="margin-right:5vw;margin-left:5vw;width:auto" class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Průměrná nálada zaměstnance</h6>
    </div>
    <div class="card-body">
        <div class="chart-bar">
            <canvas style="background-color:antiquewhite" id="myBarChart"></canvas>
            <script>
                Chart.defaults.global.defaultFontFamily = 'Nunito', '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
                Chart.defaults.global.defaultFontColor = '#858796';

                var ctx = document.getElementById("myBarChart");
                var myBarChart = new Chart(ctx, {
                    type: 'bar',

                    data: {
                        labels: @Html.Raw(Json.Serialize(Model.dateTimes)),
                        datasets: [{
                            label: "Moods",
                            backgroundColor: "#0cc0df",
                            hoverBackgroundColor: "#2e59d9",
                            borderColor: "#4e73df",

                            data: @Html.Raw(Json.Serialize(Model.sum)),
                        }],
                    },
                    options: {
                        maintainAspectRatio: false,
                        layout: {
                            padding: {
                                left: 10,
                                right: 25,
                                top: 25,
                                bottom: 0
                            }
                        },
                        scales: {
                            xAxes: [{
                                time: {
                                    unit: 'month'
                                },
                                gridLines: {
                                    display: false,
                                    drawBorder: false
                                },
                                ticks: {
                                    maxTicksLimit: 6
                                },
                                maxBarThickness: 25,
                            }],
                            yAxes: [{
                                ticks: {
                                    min: 1,
                                    max: 5,
                                    maxTicksLimit: 5,
                                    padding: 10
                                },
                                gridLines: {
                                    color: "rgb(234, 236, 244)",
                                    zeroLineColor: "rgb(234, 236, 244)",
                                    drawBorder: false,
                                    borderDash: [2],
                                    zeroLineBorderDash: [2]
                                }
                            }],
                        },
                        legend: {
                            display: false
                        },
                        tooltips: {
                            titleMarginBottom: 10,
                            titleFontColor: '#6e707e',
                            titleFontSize: 14,
                            backgroundColor: "rgb(255,255,255)",
                            bodyFontColor: "#858796",
                            borderColor: '#dddfeb',
                            borderWidth: 1,
                            xPadding: 15,
                            yPadding: 15,
                            displayColors: false,
                            caretPadding: 10
                        },
                    }
                });
            </script>
        </div>
    </div>
</div>